apiVersion: batch/v1
kind: Job
metadata:
  name: nfs-copy-job
spec:
  template:
    spec:
      containers:
      - name: nfs-copy
        image: busybox
        command: ["sh", "-c", "echo 'Sample content' > /mnt/sample.txt"]
        volumeMounts:
        - mountPath: /mnt
          name: nfs-storage
      restartPolicy: Never
      volumes:
      - name: nfs-storage
        persistentVolumeClaim:
          claimName: my-pvc
  backoffLimit: 4
