apiVersion: batch/v1
kind: Job
metadata:
  name: job
spec:
  template:
    spec:
      containers:
      - name: nfs-copy
        image: busybox
        command: ["sh", "-c", "echo '<h1>Hello world</h1>' > /mnt/index.html"]
        volumeMounts:
        - name: nfs-storage
          mountPath: /mnt
      restartPolicy: Never
      volumes:
      - name: nfs-storage
        persistentVolumeClaim:
          claimName: my-pvc
  backoffLimit: 4

