apiVersion: v1
kind: Pod
metadata:
  name: nfs-test
spec:
  containers:
  - name: nfs-test
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: nfs-storage
      mountPath: /mnt
  volumes:
  - name: nfs-storage
    persistentVolumeClaim:
      claimName: my-pvc

